version: '3'
services:
  mos:
    restart: always
    image: mos:1.0
    container_name: mos
    ports:     
      - 8080:8080
    depends_on:
      - mysqldbserver
    networks:
      - server
      
  mysqldbserver:
    image: mysql:8.0.28
    container_name: mysqldbserver
    command:
    # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
    # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    # docker的重启策略：在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # root用户的密码
      MYSQL_USER: user # 创建新用户
      MYSQL_PASSWORD: user_password # 新用户的密码
    ports:
      - 3366:3306
    volumes:
      - ~/docker/mysql/data:/var/lib/mysql
      - ~/docker/mysql/conf:/etc/mysql/conf.d
      - ~/docker/mysql/logs:/logs
    networks:
      - server
 
volumes:
  mysql-data:

networks:
  server:
    driver:
      bridge